return {
  "nvim-tree/nvim-tree.lua",
  dependencies = { "nvim-tree/nvim-web-devicons" },
  lazy = false,
  -- Disclaimer, the below function was generated by gemini :D
  config = function()
    local api = require("nvim-tree.api")

    local function on_attach(bufnr)
      local function opts(desc)
        return { desc = "nvim-tree: " .. desc, buffer = bufnr, noremap = true, silent = true, nowait = true }
      end

      api.config.mappings.default_on_attach(bufnr)

      local function add_to_quickfix()
        local mode = vim.api.nvim_get_mode().mode
        local is_visual = (mode == 'v' or mode == 'V' or mode == '')

        local items = {}

        -- Helper to build the Quickfix item
        local function process_node(node)
          if node and node.absolute_path and node.name then
            if node.type == 'directory' then return end

            table.insert(items, {
              filename = node.absolute_path,
              text = node.name,
              lnum = 1,
            })
          end
        end

        if is_visual then
          local start_line = vim.fn.line("v")
          local end_line = vim.fn.line(".")
          local min_line = math.min(start_line, end_line)
          local max_line = math.max(start_line, end_line)
          for i = min_line, max_line do
            -- Move the cursor to each line to get the node context accurately
            vim.api.nvim_win_set_cursor(0, {i, 0})
            local node = api.tree.get_node_under_cursor()
            process_node(node)
          end

          vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<Esc>", true, false, true), 'n', true)
        else
          local node = api.tree.get_node_under_cursor()
          process_node(node)
        end

        if #items > 0 then
          local qf_exists = vim.fn.getqflist()
          local was_empty = #qf_exists == 0

          vim.fn.setqflist(items, 'a')
          print("Added " .. #items .. " item(s) to Quickfix")

          if was_empty then
            vim.cmd("copen")
            vim.cmd("wincmd p")
          end
        end
      end

      vim.keymap.set({'n', 'v'}, 'q', add_to_quickfix, opts('Add to Quickfix'))
    end

    local HEIGHT_RATIO = 0.8
    local WIDTH_RATIO = 0.8

    require("nvim-tree").setup({
      on_attach = on_attach,
      sort_by = "case_sensitive",
      view = {
        float = {
          enable = true,
          open_win_config = function()
            local width = math.floor(vim.o.columns * WIDTH_RATIO)
            local height = math.floor(vim.o.lines * HEIGHT_RATIO)
            local col = math.floor((vim.o.columns - width) / 2)
            local row = math.floor((vim.o.lines - height) / 2)
            return {
              relative = "editor",
              style = "minimal",
              border = "rounded",
              row = row,
              col = col,
              width = width,
              height = height,
            }
          end,
        }
      },
      renderer = {
        add_trailing = true,
        group_empty = true,
        indent_markers = { enable = true }
      },
      filters = {
        -- dotfiles = true
      },
      git = { ignore = false }
    })
  end,
  keys = function()
    local default_opts = { noremap = true, silent = true }
    vim.api.nvim_set_keymap("n", "<leader>e", ":NvimTreeToggle<CR>",   default_opts)
    vim.api.nvim_set_keymap("n", "<leader>F", ":NvimTreeFindFile<CR>", default_opts)
    vim.api.nvim_set_keymap("n", "<leader>R", ":NvimTreeRefresh<CR>",  default_opts)
  end
}
